### ISSUE TITLE
Support for the latest version

### ISSUE THREAD

**Issue by sarkoziadam** [sg4r/proxmox-backup-client#10]
Hello,

Is it possible to support the latest version? (1.0.8-1)

**Comment by robbsie** [comment]
Should work, you could change the tag in https://github.com/sg4r/proxmox-backup-client/blob/main/pbs.build.sh

The script should checkout the latest version from the actual release I think.

**Comment by sg4r** [comment]
Hi,
I see if it's possible.
do you know what are the functionality changes of this new version ?

**Comment by uix-code** [comment]
> Hi,
> I see if it's possible.
> do you know what are the functionality changes of this new version ?

https://git.proxmox.com/?p=proxmox-backup.git;a=blob;f=debian/changelog;h=19c1bdbf678c5c1e88ea74334c273be12777bf6a;hb=8aa4842fa8cd8d039c7998027924867ad70d3696

**Comment by 1nv0k32** [comment]
Hi,
any progress on this?
there is an important change in latest update:
   * change api for incremental backups mode
that causes a failure in incremental backup with old client versions.

**Comment by sg4r** [comment]
HI,
thanks for the relaunch. I tested the modifications from version v1.0.8 to version v1.0.11, but there is a compliation problem.
I must find the problem.

**Comment by 1nv0k32** [comment]
I appreciate your time and effort...Thanks :)

**Comment by sg4r** [comment]
look at issue #12

**Comment by sg4r** [comment]
it's corrected.
can you test build and client version v1.0.11 please
