### ISSUE TITLE
Incremental file backups not working

### ISSUE THREAD

**Issue by ndgeek** [sg4r/proxmox-backup-client#19]
Have a proxmox 2.0.x server install using this backup client and it works but when it runs a second time it does not find identical files. There was an mtime issue previously that was fixed with the official client. Any chance we will see a 2.x version of the client for centos 7 anytime soon? I'd be more than willing to provide some funds to get this done.

**Comment by sg4r** [comment]
hi, i have build version 2.1.2. it work for centos8, but for centos7 it not build because old version of clang et opnssl. i must look a other days. you can find rpm for centos in release version.

**Comment by sg4r** [comment]
hi, version 2.1.2 for centos7 work afert use openssl11 form epe. you can find this rpm at https://github.com/sg4r/proxmox-backup-client/releases/tag/v2.1.2
you can check if it work for you ?
