### ISSUE TITLE
RPM for Centos 8

### ISSUE THREAD

**Issue by guillemlc** [sg4r/proxmox-backup-client#2]
Hello there!

Not an issue.

I made an RPM for Centos 8 with the binaries built following your instructions:

`[root@ndoluxel002 ~]# rpm -Uvh proxmox-backup-client-1.0.6-1.x86_64.rpm
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
        package proxmox-backup-client-1.0.6-1.x86_64 is already installed
[root@ndoluxel002 ~]# /usr/local/sbin/proxmox-backup-client version
client version: 1.0.6
[root@ndoluxel002 ~]# /usr/local/sbin/proxmox-backup-client help
Usage:

backup {<backupspec>} [OPTIONS]
benchmark [OPTIONS]
catalog dump <snapshot> [OPTIONS]
catalog shell <snapshot> <archive-name> [OPTIONS]
change-owner <group> <new-owner> [OPTIONS]
garbage-collect [OPTIONS]
help [{<command>}] [OPTIONS]
key change-passphrase [<path>] [OPTIONS]
key create [<path>] [OPTIONS]
key create-master-key
key import-master-pubkey <path>
key paperkey [<path>] [OPTIONS]
key show [<path>] [OPTIONS]
list [OPTIONS]
login [OPTIONS]
logout [OPTIONS]
map <snapshot> <archive-name> [OPTIONS]
mount <snapshot> <archive-name> <target> [OPTIONS]
prune <group> [OPTIONS]
restore <snapshot> <archive-name> <target> [OPTIONS]
snapshot files <snapshot> [OPTIONS]
snapshot forget <snapshot> [OPTIONS]
snapshot list [<group>] [OPTIONS]
snapshot notes show <snapshot> [OPTIONS]
snapshot notes update <snapshot> <notes> [OPTIONS]
snapshot upload-log <snapshot> <logfile> [OPTIONS]
status [OPTIONS]
task list [OPTIONS]
task log <upid> [OPTIONS]
task stop <upid> [OPTIONS]
unmap [<name>]
version [OPTIONS]
`
I will now see if I works fine in other systems and if the client actually works. Would you be interested in the RPM?

**Comment by sg4r** [comment]
Hi, Nice work. 
i look for use cargo rpm for build a rpm package, but if you can publish your notes to create a package 
Best regards

**Comment by sg4r** [comment]
hi, i used generate-rpm and add the dependencies. can you check if this works for you?

**Comment by guillemlc** [comment]
Hello @sg4r I used fpm **once the binaries were already built with your procedure.**

Most likely your way is better.

with fpm installed ( https://fpm.readthedocs.io/en/latest/index.html ) It is just a matter of:

`fpm -t rpm -n proxmox-backup-client -v 1.0.6 -s dir  /usr/local/sbin/proxmox-backup-client /usr/local/sbin/... `  and any other dirs.

**Comment by guillemlc** [comment]
Just as an additional comment: the client created by this method is Centos major version bound. If compiled in Centos 8 it will only work in Centos 8:

The client compiled in 8 fails to run in 7:

`Only backing up standard locations
/usr/local/sbin/proxmox-backup-client: /lib64/libfuse3.so.3: version `FUSE_3.0' not found (required by /usr/local/sbin/proxmox-backup-client)
/usr/local/sbin/proxmox-backup-client: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/sbin/proxmox-backup-client)
/usr/local/sbin/proxmox-backup-client: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /usr/local/sbin/proxmox-backup-client)
`
And no, cheating LDD is not a workaround. So it needs a el7 build. I am WIP now.

**Comment by guillemlc** [comment]
Even with fuse3-devel, the glibc will be a problem:

`
/usr/local/sbin/proxmox-backup-client: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /usr/local/sbin/proxmox-backup-client)
/usr/local/sbin/proxmox-backup-client: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /usr/local/sbin/proxmox-backup-client)
`

**Comment by sg4r** [comment]
you must build one package for the distibution version. one for centos7  and one for and centos8.
for centos7  i use fuse3-libs-3.6.1-4.el7.x86_64 from extras repo

\# yum info fuse3-libs-3.6.1-4.el7.x86_64
Loaded plugins: fastestmirror
Determining fastest mirrors
 * base: fr2.rpmfind.net
 * epel: ftp-stud.hs-esslingen.de
 * extras: miroir.univ-lorraine.fr
 * updates: mirror.in2p3.fr
Installed Packages
Name        : fuse3-libs
Arch        : x86_64
Version     : 3.6.1
Release     : 4.el7
Size        : 270 k
Repo        : installed
From repo   : extras
Summary     : File System in Userspace (FUSE) v3 libraries
URL         : http://fuse.sf.net
License     : LGPLv2+
Description : Devel With FUSE it is possible to implement a fully functional filesystem in a
            : userspace program. This package contains the FUSE v3 libraries.

**Comment by guillemlc** [comment]
Yes, it is quite clear.
