### ISSUE TITLE
Update to version 2.1.5

### ISSUE THREAD

**Issue by kingfisher77** [sg4r/proxmox-backup-client#21]
Hi, we attempted to build new version 2.1.5 with no success. We changed commit IDs but build process stopped at the patch.

Would you please be so kind as to describe the process to update the pbm.build.sh and/or the patch file? Or would you mind updating all necessary files with a short explanation?

Thank you!

**Comment by kingfisher77** [comment]
Hi, is this project actively maintained? Is someone listening?

**Comment by sg4r** [comment]
hi, i update to proxmox-backup-client 2.2.2-1. you can find rpm package for Rocky linux 8 and Fedora 36 (https://github.com/sg4r/proxmox-backup-client/releases/tag/v2.2.2)

**Comment by kingfisher77** [comment]
Perfect! Thank you. Successfully build rpm-Package to be used in Rocky Linux 8.6.

(At first, I tried to build inside a Docker Container - unsuccessfully. But does not matter.)
