### ISSUE TITLE
warning during compilaton

### ISSUE THREAD

**Issue by guillemlc** [sg4r/proxmox-backup-client#4]
In Centos 7
CentOS Linux release 7.9.2009 (Core)

`
    Finished release [optimized] target(s) in 21m 24s

   Compiling proxmox-backup v1.0.6 (/root/proxmox-backup-client/proxmox-backup)
warning: unused variable: `res`
   --> src/bin/proxmox_backup_client/mount.rs:296:13
    |
296 |             res = session_fut => {
    |             ^^^ help: if this is intentional, prefix it with an underscore: `_res`
    |
    = note: `#[warn(unused_variables)]` on by default

warning: 1 warning emitted

    Finished release [optimized] target(s) in 2m 41s
`

**Comment by sg4r** [comment]
I hope this waring will be corrected in a version greater than 1.0.6 by the proxmox development team

**Comment by sg4r** [comment]
hi, it's corrected.
can you test build and client version v1.0.11 please
