### ISSUE TITLE
failed to run custom build command for 'openssl-sys v0.9.60'

### ISSUE THREAD

**Issue by cmmh** [sg4r/proxmox-backup-client#6]
I encountered the below error.  Searching around, it seemed like adding openssl-devel might fix the problem, but it persists.  

error: failed to run custom build command for `openssl-sys v0.9.60`

Caused by:
  process didn't exit successfully: `/home/srp/proxmox-backup-client/proxmox-backup/target/release/build/openssl-sys-828e1c02a3680a96/build-script-main` (exit code: 101)
--- stdout
cargo:rustc-cfg=const_fn
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR unset
cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
OPENSSL_NO_VENDOR unset

--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', /home/srp/proxmox-backup-client/proxmox-backup/vendor/openssl-src/src/lib.rs:449:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by sg4r** [comment]
Thank you for your feedback.
I will check this in the next update

**Comment by sg4r** [comment]
hi, I just posted an update. can you check if this corrects your problem.

**Comment by cmmh** [comment]
Thank you.  Worked for me on a RHEL 8 system.  Will be trying RHEL 7 shortly.  RPM generation didn't work, but that is OK
